name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_DATABASE: redmine_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up test
      run: |
        apt-get -y install libmysqlclient-dev
        cp config/database.yml.github config/database.yml
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
